### ISSUE TITLE
random but specific crash

### ISSUE THREAD

**Issue by patrickhno** [bernerdschaefer/akephalos#73]
I have no idea even how to begin tracking this down, but we have a cucumber feature that crash randomly on a "I press" step.
It crashes most of the time, but every now and then it passes fine.

Here is the stack trace:

```
And I press "Oppfølging returer"                                                                   # features/step_definitions/web_steps.rb:28
  java.lang.NullPointerException: null (NativeException)
  (druby://127.0.0.1:56032) org/jruby/RubyKernel.java:2059:in `send'
  (druby://127.0.0.1:56032) org/jruby/RubyKernel.java:1419:in `loop'
  (druby://127.0.0.1:56032) org/jruby/RubyProc.java:268:in `call'
  (druby://127.0.0.1:56032) org/jruby/RubyProc.java:232:in `call'
  ./features/step_definitions/web_steps.rb:30:in `block (2 levels) in <top (required)>'
  ./features/step_definitions/web_steps.rb:15:in `with_scope'
  ./features/step_definitions/web_steps.rb:29:in `/^(?:|I )press "([^"]*)"(?: within "([^"]*)")?$/'
  features/logisticsweb/mainpage/mainpage.feature:100:in `And I press "Oppfølging returer"'
```

**Comment by korny** [comment]
I'm getting the same error:

```
And I press "Senden"     # features/step_definitions/web_steps.rb:26
  java.lang.NullPointerException: null (NativeException)
  (druby://127.0.0.1:58357) org/jruby/RubyKernel.java:2092:in `send'
  (druby://127.0.0.1:58357) org/jruby/RubyKernel.java:1419:in `loop'
  (druby://127.0.0.1:58357) org/jruby/RubyProc.java:274:in `call'
  (druby://127.0.0.1:58357) org/jruby/RubyProc.java:233:in `call'
  ./features/step_definitions/web_steps.rb:28
  ./features/step_definitions/web_steps.rb:13:in `with_scope'
  ./features/step_definitions/web_steps.rb:27:in `/^(?:|I )press "([^"]*)"(?: within "([^"]*)")?$/'
  features/welcome/configurator.feature:17:in `And I press "Senden"'
```

on OS X Lion 10.7.1 with Java:

```
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03-383-11A511)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02-383, mixed mode)
```

**Comment by korny** [comment]
Maybe it is using an old JRuby version?

**Comment by patrickhno** [comment]
Have you tried nerian's fork? I have submitted a patch on he's fork that probably resolves this issue.

**Comment by korny** [comment]
May work, I'll try it out.

Another solution: Update to Capybara 0.4+ and use capybara-webkit instead.

**Comment by patrickhno** [comment]
The solution to all bugs. Uninstall the software.

**Comment by korny** [comment]
:D Exactly.

So, akephalos-nerian 0.2.4 (from RubyGems) doesn't include your fix yet, but installing the latest master from the source works!

**Comment by patrickhno** [comment]
Nice! I'll leave the case open as a incentive to the maintainer to merge.
Nerian's fork is pretty much the unofficial official akephalos by now.

**Comment by Nerian** [comment]
@korny Actually that gem was never mine :) I don't know who made that one.

New development is being made here:

https://github.com/Nerian/akephalos2

Checkout the install section.
