### ISSUE TITLE
Capybara 1.0 compatibility

### ISSUE THREAD

**Issue by rb2k** [bernerdschaefer/akephalos#75]
It would be nice to be able to switch over to 1.0

**Comment by schneems** [comment]
+1, i'm interested if anyone has done any work on this, i made the attempt but got a few jruby exceptions and couldn't dig deeper.

``` ruby
#<NativeException: com.gargoylesoftware.htmlunit.ScriptException: Index: 0, Size: 0>
["(druby://127.0.0.1:59979) /Users/me/.rvm/gems/ree-1.8.7-2011.03@proj/bundler/gems/akephalos-03251d77332e/lib/akephalos/client.rb:79:in `visit'",
 "(druby://127.0.0.1:59979) org/jruby/RubyKernel.java:2096:in `send'",
 "(druby://127.0.0.1:59979) file:/Users/me/.rvm/gems/ree-1.8.7-2011.03@proj/gems/jruby-jars-1.6.4/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home/lib/ruby/1.8/drb/drb.rb:1593:in `perform_without_block'",
 "(druby://127.0.0.1:59979) file:/Users/me/.rvm/gems/ree-1.8.7-2011.03@proj/gems/jruby-jars-1.6.4/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home/lib/ruby/1.8/drb/drb.rb:1553:in `perform'",
 "(druby://127.0.0.1:59979) file:/Users/me/.rvm/gems/ree-1.8.7-2011.03@proj/gems/jruby-jars-1.6.4/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home/lib/ruby/1.8/drb/drb.rb:1627:in `main_loop'",
 "(druby://127.0.0.1:59979) org/jruby/RubyKernel.java:1419:in `loop'",
 "(druby://127.0.0.1:59979) file:/Users/me/.rvm/gems/ree-1.8.7-2011.03@proj/gems/jruby-jars-1.6.4/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home/lib/ruby/1.8/drb/drb.rb:1623:in `main_loop'",
 "(druby://127.0.0.1:59979) org/jruby/RubyProc.java:274:in `call'",
 "(druby://127.0.0.1:59979) org/jruby/RubyProc.java:233:in `call'",
 "/Users/me/.rvm/gems/ree-1.8.7-2011.03@proj/bundler/gems/akephalos-03251d77332e/lib/akephalos/capybara.rb:206:in `visit'",
 "/Users/me/.rvm/gems/ree-1.8.7-2011.03@proj/gems/capybara-1.0.1/lib/capybara/session.rb:157:in `visit'",
 "/Users/me/.rvm/gems/ree-1.8.7-2011.03@proj/gems/capybara-1.0.1/lib/capybara/dsl.rb:139:in `visit'",
 "/Users/me/Documents/projects/proj-rails/spec/acceptance/web/foo_spec.rb:36",

```

All tests for akephalos pass but 4: https://gist.github.com/1182175

If you want to play around with the (very minimal changes) you can add this to your gem file

``` ruby
  gem 'akephalos',
    :git => 'git@github.com:Schneems/akephalos.git',
    :branch => 'feature/capybara-1.x'
```

**Comment by rb2k** [comment]
https://github.com/Nerian/akephalos2 did some work on it, using it myself atm. Works fine :)
